# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ec0013348def24c184772e281f877524daf2e4e37790fff5e733e0bd23a79b864dfe6ce5d41b2877e14ebbc371f59eb8fe596c754c42bd8e066ddb233385b7
  pag_seguro_email: pixelzip0@gmail.com
  pag_seguro_token: ED99460F3C75449E9F5F665AED134105
  s3_access_key_id: AKIAJBYHTCMXQTSSLXFQ
  s3_secret_access_key: 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
  app_id_face: 1958219931100778
  app_secret_face: f92dceb9770029476c3dbc5d28816950
  sender_email: admin@development.com

test:
  secret_key_base: 4bee254f4908a529121ae55ffef1d3180fd6be909c7b1735da63f58db5bed80749bf1aabac7708deb1b328cb0242166acce96bad796dab5069fdcbee2bfb2a43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_access_key_id: <%= ENV["S3_KEY_ID"] %>
  s3_secret_access_key: <%= ENV["S3_SECRET_KEY"] %>
  airbrake_project_id: <%= ENV['AIRBRAKE_PROJECT_ID'] %>
  airbrake_project_key: <%= ENV['AIRBRAKE_API_KEY'] %>
  app_id_face: <%= ENV['APP_ID_FACE'] %>
  app_secret_face: <%= ENV['APP_SECRET_FACE'] %>
  sender_email: <%= ENV["ADMIN_EMAIL"] %>